import Head from 'next/head'
// components
import { MainContent } from '../components/mainContent'
// styles
import styles from '../styles/home.module.css'

export default function Home () {
  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MainContent />
    </div>
  )
}
